recipes-support: Add libqrtr-glib recipe
ndechesne/meta-qcom pull request #406
Opened 2021-12-16 17:04 UTC by loicpoulain

libqrtr-glib is a glib-based library to use and manage the
QRTR (Qualcomm IPC Router) bus. It is used by tools or other
libraries such as libqmi to communicate with remote services
such as ones exposed the by modem.

Signed-off-by: Loic Poulain <loic.poulain@linaro.org>

2021-12-17 07:44 UTC, lumag requested changes

2021-12-17 07:44 UTC, lumag commented on recipes-support/libqrtr-glib/libqrtr-glib_1.0.0.bb
> +	       QRTR (Qualcomm IPC Router) bus"
This would end up with the huuge gap in the description (unless it's sanitized) by bitbake. So I'd suggest to remove extra indentation here.

2021-12-17 07:44 UTC, lumag commented on recipes-support/libqrtr-glib/libqrtr-glib_1.0.0.bb
> +
Extra empty line

2021-12-17 08:16 UTC, ndechesne commented
Given that libqmi is in meta-oe, doesn't that make more sense to get this one into meta-oe too? then you can also include a PACKAGECONFIG in qmi to enable the qrtr support?

2021-12-17 12:55 UTC, loicpoulain commented
> Given that libqmi is in meta-oe, doesn't that make more sense to get this one into meta-oe too? then you can also include a PACKAGECONFIG in qmi to enable the qrtr support?

yes probably, I was thinking about libqrtr-glib as a BSP layer lib specific to qcom, but given qualcomm people expect to use that also over PCIe (and even USB), I'll submit it meta-oe, with comments addressed.

2021-12-21 09:11 UTC, ndechesne commented
ok, then closing it here.

2021-12-21 09:11 UTC, closed without merging